FROM --platform=linux/arm64 bitnami/spark:3.5.3

# Cài đặt OpenJDK 17
USER root

RUN apt-get update && \
    apt-get install -y openjdk-17-jdk && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Thiết lập biến môi trường JAVA_HOME
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-arm64
ENV PATH="$JAVA_HOME/bin:$PATH"
ENV PATH="/opt/bitnami/spark/bin:$PATH"
ENV SPARK_MASTER_URL=spark://spark-master:7077

USER bitnami
