# Dockerfile.airflow
FROM apache/airflow:2.6.0-python3.9

USER root

# Cài đặt OpenJDK 11 và procps
RUN apt-get update && \
    apt-get install -y openjdk-11-jdk procps && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Thiết lập biến môi trường JAVA_HOME
ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
ENV PATH="$JAVA_HOME/bin:$PATH"

USER airflow
