FROM --platform=linux/arm64 bitnami/spark:3.2.0

# Cài đặt OpenJDK 11
USER root

RUN apt-get update && \
    apt-get install -y openjdk-11-jdk && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Thiết lập biến môi trường JAVA_HOME
ENV JAVA_HOME=/opt/bitnami/java
ENV PATH="$JAVA_HOME/bin:$PATH"
ENV SPARK_MASTER_URL=spark://spark-master:7077

USER bitnami